#ifndef FASTLLM_HIP_DECL_H_
#define FASTLLM_HIP_DECL_H_

#ifdef USE_ROCM

// HIP function declarations for MSVC host compilation
// These functions are defined in .hip files and compiled into hip_fastllm.lib

extern bool FastllmBF16ToFloat(void *a, void *b, int len);
extern bool FastllmBF16ToHalf(void *a, void *b, int len);
extern bool FastllmCudaAdd(const fastllm::Data &input, float v, fastllm::Data &output);
extern bool FastllmCudaAddTo(fastllm::Data &input0, const fastllm::Data &input1, float alpha);
extern bool FastllmCudaAlibiMask(fastllm::Data &input, const fastllm::Data &mask, float maskValue);
extern bool FastllmCudaApplyChunkDecayByLastLogG(fastllm::Data &input, const fastllm::Data &g);
extern bool FastllmCudaApplyLognAttn(fastllm::Data &input, fastllm::Data &lognAttn, fastllm::Data &positionIds);
extern bool FastllmCudaAttention(const fastllm::Data &q, const fastllm::Data &k, const fastllm::Data &v, const fastllm::Data &mask, const fastllm::Data &output, int group, float scale, int maskType);
extern bool FastllmCudaAttentionBatch(fastllm::Data **q, fastllm::Data **k, fastllm::Data **v, fastllm::Data **mask, fastllm::Data **output, int group, float scale, int batch);
extern bool FastllmCudaAttentionMask(fastllm::Data &input, const fastllm::Data &mask, float maskValue);
extern bool FastllmCudaBatchMatMul(const fastllm::Data &input0, const fastllm::Data &input1, fastllm::Data &output, int input0Spatial, int input1Spatial, int outputSpatial, int input0Stride, int input1Stride, int batch, int n, int m, int k, float alpha);
extern bool FastllmCudaBatchMatMulBatch(void **i0s, void **i1s, void **os, int *ns, int *ms, int *ks, int *i0Strides, int *i1Strides, float alpha, int batch);
extern bool FastllmCudaBatchMatMulTransB(const fastllm::Data &input0, const fastllm::Data &input1, fastllm::Data &output, int input0Spatial, int input1Spatial, int outputSpatial, int input0Stride, int input1Stride, int batch, int n, int m, int k, float alpha);
extern bool FastllmCudaBatchMatMulTransBBatch(void **i0s, void **i1s, void **os, int *ns, int *ms, int *ks, int *i0Strides, int *i1Strides, float alpha, int batch);
extern bool FastllmCudaBFloat16MatMulBFloat16(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaBFloat16MatMulFloat16(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaBFloat16MatMulFloat32(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaBFloat16MatMulFP8E4M3(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaBFloat16MatMulFP8E4M3AddTo(const fastllm::Data &input, fastllm::Data &weight, fastllm::Data &output, float alpha, bool overwrite, int n, int m, int k);
extern bool FastllmCudaBFloat16MatMulFP8E4M3Block128(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaBFloat16MatMulFP8E4M3Block128AddTo(const fastllm::Data &input, fastllm::Data &weight, fastllm::Data &output, float alpha, bool overwrite, int n, int m, int k);
extern bool FastllmCudaBFloat16MatMulFP8E4M3Block128Swiglu(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaBFloat16MatMulFP8E4M3Swiglu(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaBFloat16MatMulGGUF(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaBFloat16MatMulInt4Group(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaBFloat16MatMulInt4Group128(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaBFloat16MatMulNVFP4(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaBFloat16MatMulNVFP4Block16(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaBFloat16MatMulNVFP4Block16E8M0(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaBFloat16MergeMOEFP8E4M3Batch1(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &output, fastllm::Data **gateups, fastllm::Data **downs, const float *scores, bool scoresOnCuda, int topk, int hidden, int inter);
extern bool FastllmCudaBFloat16MergeMOEFP8E4M3Batch1Indexed(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &output, fastllm::Data **weights, int weightsBatch, const int32_t *indices, const float *scores, int topk, int hidden, int inter);
extern bool FastllmCudaBFloat16MergeMOEFP8E4M3GroupedIndexed(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &w2, fastllm::Data &output, fastllm::Data **weights, int weightsBatch, const int *routeRows, const float *routeScales, const int *routePositions, const int *expertStarts, const int *expertCounts, int batch, int topk, int totalTasks, int maxExpertTasks, int hidden, int inter);
extern bool FastllmCudaBFloat16MergeMOEFP8E4M3SmallBatchIndexed(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &output, fastllm::Data **weights, int weightsBatch, const int32_t *indices, const float *scores, int batch, int topk, int hidden, int inter);
extern bool FastllmCudaBFloat16MergeMOEGGUFBatch1(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &output, fastllm::Data **gateups, fastllm::Data **downs, const float *scores, bool scoresOnCuda, int topk, int hidden, int inter);
extern bool FastllmCudaBFloat16MergeMOENVFP4Batch1(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &output, fastllm::Data **gateups, fastllm::Data **downs, const float *scores, bool scoresOnCuda, int topk, int hidden, int inter);
extern bool FastllmCudaBFloat16MergeMOENVFP4Batch1Indexed(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &output, fastllm::Data **weights, int weightsBatch, const int32_t *indices, const float *scores, int topk, int hidden, int inter);
extern bool FastllmCudaBFloat16MergeMOENVFP4GroupedIndexed(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &w2, fastllm::Data &output, fastllm::Data **weights, int weightsBatch, const int *routeRows, const float *routeScales, const int *routePositions, const int *expertStarts, const int *expertCounts, int batch, int topk, int totalTasks, int maxExpertTasks, int hidden, int inter);
extern bool FastllmCudaBFloat16MergeMOENVFP4SmallBatchIndexed(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &output, fastllm::Data **weights, int weightsBatch, const int32_t *indices, const float *scores, int batch, int topk, int hidden, int inter);
extern bool FastllmCudaCatBatch(fastllm::Data **inputs, fastllm::Data &output, int axis);
extern bool FastllmCudaCausalMask(fastllm::Data &input, int base, float maskValue);
extern bool FastllmCudaConv1DPerChannelFloat32(const fastllm::Data &input, fastllm::Data &weight, fastllm::Data &bias, int inputChannels, int outputChannels, int kernelSize, int stride, int padding, fastllm::Data &output);
extern bool FastllmCudaConv1DPerChannelSiluSingleTokenFloat16(const fastllm::Data &input, fastllm::Data &weight, fastllm::Data &bias, fastllm::Data &output);
extern bool FastllmCudaConv2DFloat32(const fastllm::Data &input, fastllm::Data &weight, fastllm::Data &bias, int inputChannels, int outputChannels, int kernelH, int kernelW, int strideH, int strideW, int padH, int padW, fastllm::Data &output);
extern bool FastllmCudaCopy(const fastllm::Data &input, fastllm::Data &output);
extern bool FastllmCudaCrossSwiglu(const fastllm::Data &input, fastllm::Data &output);
extern bool FastllmCudaCumSumLastDim(fastllm::Data &input);
extern bool FastllmCudaEmbedding(const fastllm::Data &input, const fastllm::Data &weight, fastllm::Data &output);
extern bool FastllmCudaEmbeddingDirect(const fastllm::Data &input, const fastllm::Data &weight, fastllm::Data &output);
extern bool FastllmCudaExp(const fastllm::Data &input, fastllm::Data &output);
extern bool FastllmCudaFloatMergeMOEGGUFBatch1(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &output, fastllm::Data **gateups, fastllm::Data **downs, const float *scores, bool scoresOnCuda, int topk, int hidden, int inter);
extern bool FastllmCudaGeglu(const fastllm::Data &input, fastllm::Data &output);
extern bool FastllmCudaGelu(const fastllm::Data &input, fastllm::Data &output);
extern bool FastllmCudaGeluNew(const fastllm::Data &input, fastllm::Data &output);
extern bool FastllmCudaHalfAttention(const fastllm::Data &q, const fastllm::Data &k, const fastllm::Data &v, const fastllm::Data &mask, const fastllm::Data &output, int group, float scale, int maskType);
extern bool FastllmCudaHalfMatMulBFloat16(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaHalfMatMulFloat16(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k, bool addTo);
extern bool FastllmCudaHalfMatMulFloat16AddToNoBias(const fastllm::Data &input, fastllm::Data &weight, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaHalfMatMulFloat16Swiglu(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaHalfMatMulFloat32(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaHalfMatMulFloatFP8E4M3(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaHalfMatMulFloatFP8E4M3AddTo(const fastllm::Data &input, fastllm::Data &weight, fastllm::Data &output, float alpha, bool overwrite, int n, int m, int k);
extern bool FastllmCudaHalfMatMulFloatFP8E4M3Block128(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaHalfMatMulFloatFP8E4M3Block128AddTo(const fastllm::Data &input, fastllm::Data &weight, fastllm::Data &output, float alpha, bool overwrite, int n, int m, int k);
extern bool FastllmCudaHalfMatMulFloatFP8E4M3Block128Swiglu(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaHalfMatMulFloatFP8E4M3Swiglu(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaHalfMatMulFloatInt4Group(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaHalfMatMulFloatInt4Group128(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaHalfMatMulFloatInt4NoZero(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaHalfMatMulFloatInt8(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaHalfMatMulFloatNVFP4(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaHalfMatMulFloatNVFP4Block16(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaHalfMatMulFloatNVFP4Block16E8M0(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaHalfMatMulGGUF(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaHalfMergeMOEFP8E4M3Batch1(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &output, fastllm::Data **gateups, fastllm::Data **downs, const float *scores, bool scoresOnCuda, int topk, int hidden, int inter);
extern bool FastllmCudaHalfMergeMOEFP8E4M3Batch1Indexed(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &output, fastllm::Data **weights, int weightsBatch, const int32_t *indices, const float *scores, int topk, int hidden, int inter);
extern bool FastllmCudaHalfMergeMOEFP8E4M3GroupedIndexed(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &w2, fastllm::Data &output, fastllm::Data **weights, int weightsBatch, const int *routeRows, const float *routeScales, const int *routePositions, const int *expertStarts, const int *expertCounts, int batch, int topk, int totalTasks, int maxExpertTasks, int hidden, int inter);
extern bool FastllmCudaHalfMergeMOEFP8E4M3SmallBatchIndexed(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &output, fastllm::Data **weights, int weightsBatch, const int32_t *indices, const float *scores, int batch, int topk, int hidden, int inter);
extern bool FastllmCudaHalfMergeMOEGGUFBatch1(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &output, fastllm::Data **gateups, fastllm::Data **downs, const float *scores, bool scoresOnCuda, int topk, int hidden, int inter);
extern bool FastllmCudaHalfMergeMOENVFP4Batch1(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &output, fastllm::Data **gateups, fastllm::Data **downs, const float *scores, bool scoresOnCuda, int topk, int hidden, int inter);
extern bool FastllmCudaHalfMergeMOENVFP4Batch1Indexed(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &output, fastllm::Data **weights, int weightsBatch, const int32_t *indices, const float *scores, int topk, int hidden, int inter);
extern bool FastllmCudaHalfMergeMOENVFP4GroupedIndexed(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &w2, fastllm::Data &output, fastllm::Data **weights, int weightsBatch, const int *routeRows, const float *routeScales, const int *routePositions, const int *expertStarts, const int *expertCounts, int batch, int topk, int totalTasks, int maxExpertTasks, int hidden, int inter);
extern bool FastllmCudaHalfMergeMOENVFP4SmallBatchIndexed(const fastllm::Data &input, fastllm::Data &w1, fastllm::Data &output, fastllm::Data **weights, int weightsBatch, const int32_t *indices, const float *scores, int batch, int topk, int hidden, int inter);
extern bool FastllmCudaHalfPagedAttention(fastllm::Data &q, fastllm::Data &k, fastllm::Data &v, fastllm::Data &output, int group, float scale, bool inited);
extern bool FastllmCudaHalfPagedAttention(fastllm::Data&, fastllm::Data&, fastllm::Data&, fastllm::Data&, int, int, int, float, int, int, int, int, int, int, int, int, int, float, int, int);
extern bool FastllmCudaHalfPagedAttentionBatch(fastllm::Data &q, fastllm::Data &kCaches, fastllm::Data &vCaches, fastllm::Data &qSizes, fastllm::Data &pageSizes, fastllm::Data &pageIndexs, fastllm::Data &lastPageLens, fastllm::Data &output, int group, float scale, int attentionType, bool inited, bool sync);
extern bool FastllmCudaHalfPagedAttentionBatch(fastllm::Data&, fastllm::Data&, fastllm::Data&, fastllm::Data*, fastllm::Data*, fastllm::Data*, int, int, int, float, int, int, int, int, int, int, int, int, float, int, int);
extern bool FastllmCudaHostRegister(void *ptr, size_t size);
extern bool FastllmCudaLayerNorm(const fastllm::Data &input, fastllm::Data &gamma, fastllm::Data &beta, fastllm::Data &output, int axis);
extern bool FastllmCudaLlama3RopeEncoding(fastllm::Data &data, const fastllm::Data &positionIds, int rotaryDim, float ropeTheta, float factor, float originalMaxPosition, float lowFreqFactor, float highFreqFactor);
extern bool FastllmCudaLlamaRotatePosition2D(fastllm::Data &data, const fastllm::Data &positionIds, const fastllm::Data &sinData, const fastllm::Data &cosData, int rotaryDim);
extern bool FastllmCudaLlamaRotatePosition2DPart(fastllm::Data &data, const fastllm::Data &positionIds, const fastllm::Data &sinData, const fastllm::Data &cosData, int rotaryDim, int part);
extern bool FastllmCudaMakeDecayMask(fastllm::Data &input, fastllm::Data &output);
extern bool FastllmCudaMambaSoftplus(const fastllm::Data &input, fastllm::Data &output, fastllm::Data &aLogData, fastllm::Data &dtBiasData);
extern bool FastllmCudaMatMulBFloat16(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaMatMulFloat16(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaMatMulFloat32(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaMatMulFloatFP8E4M3(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaMatMulFloatFP8E4M3Block128(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaMatMulFloatGGUF(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaMatMulFloatInt4(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaMatMulFloatInt4Group(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaMatMulFloatInt4NoZero(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaMatMulFloatInt8(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaMatMulFloatNVFP4(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaMatMulFloatNVFP4Block16(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaMatMulFloatNVFP4Block16E8M0(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &bias, fastllm::Data &output, int n, int m, int k);
extern bool FastllmCudaMLA(const fastllm::Data &qNope, const fastllm::Data &qPe, const fastllm::Data &kvCache, const fastllm::Data &peCache, fastllm::Data &ss, fastllm::Data &output, float softmaxScale);
extern bool FastllmCudaMLAPaged(const fastllm::Data &qNope, const fastllm::Data &qPe, const fastllm::Data &kvCachePaged, const fastllm::Data &peCachePaged, fastllm::Data &output, float softmaxScale);
extern bool FastllmCudaMLAPaged(const fastllm::Data&, const fastllm::Data&, const fastllm::Data&, const fastllm::Data&, const fastllm::Data&, fastllm::Data&, int, int, int, int, float, int);
extern bool FastllmCudaMul(const fastllm::Data &input, float v, fastllm::Data &output);
extern bool FastllmCudaMulBatch(fastllm::Data **inputs, float v, int batch, fastllm::Data **outputs);
extern bool FastllmCudaMulTo(fastllm::Data &input0, const fastllm::Data &input1, float alpha);
extern bool FastllmCudaNearlyRotatePosition2D(fastllm::Data &data, const fastllm::Data &positionIds, const fastllm::Data &sinData, const fastllm::Data &cosData, int rotaryDim, int positionStride);
extern bool FastllmCudaPermute(fastllm::Data &input, const std::vector<int> &axis);
extern bool FastllmCudaQKVRMSNormRope(fastllm::Data &qkv, fastllm::Data &qNormWeight, fastllm::Data &kNormWeight, const fastllm::Data &positionIds, int q_heads, int k_heads, int head_dim, int rotateDim, float eps, float ropeTheta, float ropeScale);
extern bool FastllmCudaQKVRMSNormRopeSplitAppendPagedCache(fastllm::Data &qkv, fastllm::Data &qNormWeight, fastllm::Data &kNormWeight, const fastllm::Data &positionIds, fastllm::Data &qOutput, uint8_t *pagedKData, uint8_t *pagedVData, int32_t *insertIndexs, int32_t *insertPositions, int32_t *lastPageLens, int q_heads, int k_heads, int head_dim, int rotateDim, float eps, float ropeTheta, float ropeScale, int pageLen, fastllm::DataType pagedDataType, int batch, int doQKNorm);
extern bool FastllmCudaQwen35InterleavedRope(fastllm::Data &data, const fastllm::Data &positionIds, int rotaryDim, int sectionT, int sectionH, int sectionW, float ropeTheta, float ropeScale);
extern bool FastllmCudaRelu(const fastllm::Data &input, fastllm::Data &output);
extern bool FastllmCudaRepeatPenalty(fastllm::Data &input, fastllm::Data &penalty, fastllm::Data &penaltyScale);
extern bool FastllmCudaRMSNorm(const fastllm::Data &input, fastllm::Data &weight, fastllm::Data &output, float eps);
extern bool FastllmCudaRMSNormPart(const fastllm::Data &input, fastllm::Data &weight, fastllm::Data &output, float eps, int start, int end);
extern bool FastllmCudaRMSNormPartApply(const fastllm::Data &input, fastllm::Data &weight, fastllm::Data &output, const float *sumIn, float eps, int start, int end, int partChannelsGlobal);
extern bool FastllmCudaRMSNormPartSum2(const fastllm::Data &input, float *sumOut, int start, int end);
extern bool FastllmCudaRMSNormSiluMulFloat16(const fastllm::Data &input, fastllm::Data &weight, const fastllm::Data &gateInput, fastllm::Data &output, float eps);
extern bool FastllmCudaRopeEncoding(fastllm::Data &data, const fastllm::Data &positionIds, int rotaryDim, float ropeTheta, float ropeScale);
extern bool FastllmCudaRotatePosition2D(fastllm::Data &data, const fastllm::Data &positionIds, const fastllm::Data &sinData, const fastllm::Data &cosData, int rotaryDim);
extern bool FastllmCudaSelectExpert(const fastllm::Data &logits, const fastllm::Data *gateBias, fastllm::Data &index, fastllm::Data &score, int topk, bool needNorm, float routeScale);
extern bool FastllmCudaShiftAppendConv1DPerChannelSiluSingleTokenFloat16(fastllm::Data &cache, const fastllm::Data &newToken, fastllm::Data &weight, fastllm::Data &bias, fastllm::Data &output);
extern bool FastllmCudaShiftAppendConv1DPerChannelSiluSingleTokenFloat16BatchPointers(const std::vector<fastllm::Data*> &caches, const fastllm::Data &newToken, fastllm::Data &weight, fastllm::Data &bias, fastllm::Data &output);
extern bool FastllmCudaSigmoid(const fastllm::Data &input, fastllm::Data &output);
extern bool FastllmCudaSigmoidMambaSoftplus(fastllm::Data &sigmoidInputOutput, const fastllm::Data &softplusInput, fastllm::Data &softplusOutput, const fastllm::Data &aLogData, const fastllm::Data &dtBiasData);
extern bool FastllmCudaSilu(const fastllm::Data &input, fastllm::Data &output);
extern bool FastllmCudaSoftmax(const fastllm::Data &input, fastllm::Data &output, int axis);
extern bool FastllmCudaSoftmaxBatch(fastllm::Data **inputs, fastllm::Data **outputs, int axis, int batch);
extern bool FastllmCudaSplitBatch(fastllm::Data &input, fastllm::Data **outputs, int axis);
extern bool FastllmCudaSwiglu(const fastllm::Data &input, fastllm::Data &output);
extern bool FastllmCudaTopK(const fastllm::Data &input, fastllm::Data &output, int topk);
extern bool FastllmCudaTopKTopPSampling(float *logits, float *temperatures, int *topKArr, float *topPArr, int *output, int batch, int vocabSize);
extern bool FastllmCudaTransferAttn(fastllm::Data &input);
extern bool FastllmFloatToBF16(void *a, void *b, int len);
extern bool FastllmFloatToHalf(void *a, void *b, int len);
extern bool FastllmHalfToBF16(void *a, void *b, int len);
extern bool FastllmHalfToFloat(void *a, void *b, int len);
extern int FastllmCudaGetDevice();
extern int FastllmCudaGetDeviceCount();
extern size_t FastllmCudaGetWeightSlabBytes();
extern void FastllmChunkGatedDeltaRulePrefill(fastllm::Data &q, fastllm::Data &k, fastllm::Data &v, fastllm::Data &g, fastllm::Data &attn, fastllm::Data &k_cumdecay, fastllm::Data &last_recurrent_state, fastllm::Data &core_attn_out);
extern void FastllmCudaAddHostToDevice(void *dst, void *hostSrc, int len, fastllm::DataType dataType);
extern void FastllmCudaClearBigBuffer();
extern void FastllmCudaCopyFromDeviceToDevice(void *dst, void *src, size_t size);
extern void FastllmCudaCopyFromDeviceToHost(void *dst, void *src, size_t size);
extern void FastllmCudaCopyFromHostToDevice(void *dst, void *src, size_t size);
extern void FastllmCudaCopyFromHostToDeviceAsync(void *dst, void *src, size_t size, void *stream);
extern void FastllmCudaCopyFromPinnedHostToDevice(void *dst, void *src, size_t size);
extern void FastllmCudaCopyFromPinnedHostToDeviceAsync(void *dst, void *src, size_t size, void *stream);
extern void FastllmCudaDirectFree(void *ret);
extern void FastllmCudaEventDestroy(void *event);
extern void FastllmCudaEventRecord(void *event, void *stream);
extern void FastllmCudaEventSynchronize(void *event);
extern void FastllmCudaFinishInput(const fastllm::Data &input, void *data);
extern void FastllmCudaFinishOutput(fastllm::Data &output, void *data);
extern void FastllmCudaFP8E4M3EnsureScalesAndBiasOnDevice(fastllm::Data &weight, const fastllm::Data &bias, int k);
extern void FastllmCudaFree(void *ret);
extern void FastllmCudaHostFree(void *ptr);
extern void FastllmCudaHostUnregister(void *ptr);
extern void FastllmCudaMallocBigBuffer(size_t size);
extern void FastllmCudaMemcpy2DDeviceToDevice(void *dst, size_t dpitch, const void *src, size_t spitch, size_t width, size_t height);
extern void FastllmCudaMemcpy2DDeviceToDeviceAuto(void *dst, size_t dpitch, const void *src, size_t spitch, size_t width, size_t height, int dstDevice, int srcDevice);
extern void FastllmCudaMemcpy2DDeviceToDeviceBatch(void **dsts, size_t *dpitchs, void **srcs, size_t *spitchs, size_t *widths, size_t *heights, int batch);
extern void FastllmCudaMemcpyBetweenDevices(int dstId, void *dst, int srcId, void *src, size_t size);
extern void FastllmCudaMemPoolStats();
extern void FastllmCudaMemset0(void *ret, size_t size);
extern void FastllmCudaPagedCacheCopy(uint8_t *pagedData, int pageIdx, int pageLen, int numHeads, int headDim, fastllm::DataType dstType, uint8_t *inputData, fastllm::DataType srcType, int seqLen, int inputOffset, int copyLen, int pageOffset);
extern void FastllmCudaPagedCacheCopyBatch(uint8_t *pagedData, int32_t *pageIdxArray, int32_t *pageOffsetArray, int pageLen, int batch, int numHeads, int headDim, fastllm::DataType dstType, uint8_t *inputData, fastllm::DataType srcType);
extern void FastllmCudaPickInput(uint8_t *input, uint8_t *partInput, int rows, int cols, int *index);
extern void FastllmCudaPickOutput(float *partOutput, float *output, int rows, int cols, int *index, float *scales);
extern void FastllmCudaPickOutput(uint8_t *partOutput, uint8_t *output, int rows, int cols, int *index, float *scales, fastllm::DataType dataType);
extern void FastllmCudaRepeat(void *input, void *output, int outer, int repeatTimes, int inputStride, int outputStride0, int outputStride1, int copyLen);
extern void FastllmCudaSetDevice(int gpu_id);
extern void FastllmCudaSetWeightSlabBytes(size_t bytes);
extern void FastllmCudaShiftAppendWindow(uint8_t *cache, const uint8_t *newToken, int channels, int window, int unitSize);
extern void FastllmCudaStreamDestroy(void *stream);
extern void FastllmCudaStreamSynchronize(void *stream);
extern void FastllmCudaStreamWaitEvent(void *stream, void *event);
extern void FastllmPickInput(uint8_t *input, uint8_t *partInput, int rows, int cols, int *cudaIndex);
extern void FastllmRecurrentGatedDeltaRule(fastllm::Data &q, fastllm::Data &k, fastllm::Data &v, fastllm::Data &g, fastllm::Data &b, fastllm::Data &last_recurrent_state, fastllm::Data &core_attn_out, float qScale);
extern void FastllmRecurrentGatedDeltaRuleBatch(fastllm::Data &q, fastllm::Data &k, fastllm::Data &v, fastllm::Data &g, fastllm::Data &b, std::vector<fastllm::Data*> &last_recurrent_states, fastllm::Data &core_attn_out, float qScale);
extern void FastllmRecurrentGatedDeltaRuleBatchFromConvBa(fastllm::Data &convOutput, fastllm::Data &ba, fastllm::Data &normWeight, fastllm::Data &aLog, fastllm::Data &dtBias, std::vector<fastllm::Data*> &last_recurrent_states, fastllm::Data &core_attn_out, int numKHeads, int numVHeads, int headKDim, int headVDim, float eps, float qScale);
extern void FastllmReduce(uint8_t *output, uint8_t *partOutput, int len, int threadNum, fastllm::DataType dataType);
extern void FastllmReleaseDequantScratch(void *ptr, bool own);
extern void FastllmResetLogitsOfEOS(int batch, fastllm::Data *logits, const std::vector<int> res_lens, const std::vector<int> eos_nums, const std::vector<int> eos_ids);
extern void FastllmResetLogitsOfEOSAll(int batch, fastllm::Data *logits, const std::vector<int> &eos_ids);

// DeepSeekV4 specific ops
extern bool FastllmCudaDeepSeekV4ScaleQRotary(fastllm::Data&, int, float, int, int, float, int, int, float);
extern bool FastllmCudaDeepSeekV4RotaryQuant(fastllm::Data&, int, float, int, int, float, int, int, int, int, int);
extern bool FastllmCudaDeepSeekV4RouteScoreTransform(fastllm::Data&, int);
extern bool FastllmCudaDeepSeekV4HcPre(const fastllm::Data&, fastllm::Data&, fastllm::Data&, fastllm::Data&, int, int, float, float, fastllm::Data&, fastllm::Data&, fastllm::Data&);
extern bool FastllmCudaDeepSeekV4WoA(const fastllm::Data&, const fastllm::Data&, int, int, fastllm::Data&);
extern bool FastllmCudaDeepSeekV4HcPost(const fastllm::Data&, const fastllm::Data&, const float*, const float*, int, int, int, int, fastllm::Data&);
extern bool FastllmCudaDeepSeekV4StoreWindowKVCache(const fastllm::Data&, int, int, fastllm::Data&);
extern bool FastllmCudaDeepSeekV4UpdateWindowKVCache(const fastllm::Data&, int, int, fastllm::Data&);
extern bool FastllmCudaDeepSeekV4BuildCompressedKV(const fastllm::Data&, const fastllm::Data&, const fastllm::Data&, int, int, int, int, int, int, int, bool, fastllm::Data&);
extern bool FastllmCudaDeepSeekV4SparseAttentionDecodeCached(const fastllm::Data&, const fastllm::Data&, const fastllm::Data&, fastllm::Data&, int, int, int, int, float, int, float, int, int, float, fastllm::Data&);
extern bool FastllmCudaDeepSeekV4SparseAttentionPrefill(const fastllm::Data&, const fastllm::Data&, fastllm::Data&, int, int, int, int, float, int, float, int, int, float, fastllm::Data&, int);
extern bool FastllmCudaDeepSeekV4HashRouteScore(const fastllm::Data&, fastllm::Data&, const int*, int, int, int, float, fastllm::Data&, fastllm::Data&);

extern "C" {
extern bool FastllmCudaDeepSeekV4SparseAttentionDecodeCachedBatch(const std::vector<fastllm::Data*> &qParts, const std::vector<fastllm::Data*> &windowKVs, const std::vector<fastllm::Data*> &compressedKVs, fastllm::Data &attnSink, int windowSize, const std::vector<int> &startPositions, const std::vector<int> &compressedCounts, int ropeDim, float ropeBase, int originalSeqLen, float ropeFactor, int betaFast, int betaSlow, float softmaxScale, fastllm::Data &output);
extern bool FastllmCudaDeepSeekV4HcPostCudaMix(const fastllm::Data &x, const fastllm::Data &residual, const fastllm::Data &post, const fastllm::Data &comb, int bsz, int seqlen, int hcMult, int dim, fastllm::Data &output);
extern bool FastllmCudaDeepSeekV4BuildWindowKVPrefix(const fastllm::Data &windowKV, int startPos, int windowSize, int prefixLen, fastllm::Data &output);
} // extern "C"

// Utility functions
extern std::vector<long long> FastllmCudaGetFreeSizes();
extern std::vector<long long> FastllmCudaGetTotalSizes();

#endif // USE_ROCM

#endif // FASTLLM_HIP_DECL_H_
